### PR TITLE
Laravel 6.0 support

### PR DESCRIPTION
**Pull request by websmurf**
I've added some php versions to the check as well

### CODE REVIEW

**Comment by jasperf** [comment]
Looks good and better than my request. Would be great to have this merged. Unless we need a solution that does not require https://github.com/laravel/helpers . Up to Hidecco. Would be great to have this done though.

**Comment by jasperf** [comment]
Is there any news on this pull request @hiddeco and @petericebear ? Would love to get the Laravel 6 support.

**Comment by hiddeco** [comment]
Sorry folks, I am pretty busy in another ecosystem of this magic world of ours and this slipped through the cracks.

Given I am no longer doing anything related to PHP, nor planning to get into this world again soon, I leave it up to you guys what your future vision is (and if `laravel/helpers` is still required).

Happy to merge whatever you can proof is best (still able to review changes, but no longer actively following the ecosystem which makes decision making harder).

**Comment by petericebear** [comment]
I merged the Pull Request, thanks for submitting it. I will tag a new version for the release.
There is a new API upcoming for TransIP and currently working on it as a package. 
It has more features than the current API and the package will be framework agnostic. Will share the details soon about it.

**Comment by jasperf** [comment]
> There is a new API upcoming for TransIP and currently working on it as a package.

Music to my ears @petericebear . Can't wait to see it in action!

**Pull request merged**
