### PR TITLE
Adding Support to 5.7

### PR DESCRIPTION
**Pull request by a1tem**

### CODE REVIEW

**Comment by basepack** [comment]
Hi,

Can you please merge this with master? So that we do not need to create a fork just for this.

Thanks!

**Review by petericebear — CHANGES_REQUESTED** [review]
Can you add 5.8 also with it?

**Comment by petericebear** [comment]
I am checking why the Travis build errors on PHP 7.1. And adding 5.8 support also

**Comment by petericebear** [comment]
There were other changes needed, I adjusted the code in another branche and added Laravel 5.8 also.
Merged to Master and tagged a new version. Happy coding!

**Pull request closed without merging**
