### PR TITLE
Updated to latest version of the TransIP package

### PR DESCRIPTION
**Pull request by petericebear**
Maybe a suggestion to make the Namespace like something as LaravelTransip?

### CODE REVIEW

**Comment by hiddeco** [comment]
@petericebear or `TransIP\Laravel` to keep it consistent.

**Comment by petericebear** [comment]
Ah yes that would be nice indeed. This commit is for 5.3 off the API. Do you version it with that new namespace?

**Comment by hiddeco** [comment]
@petericebear I'll make the (version) changes later this week as I'm quite busy right now. Will keep you posted.

**Comment by petericebear** [comment]
Hi Hiddeco,
Any chance to look into this?
Greetings,
Peter

**Comment by hiddeco** [comment]
@petericebear sorry for the delay, version `v5.2` and `v5.3` are now officially available 🎉 

See the [changelog](https://github.com/hiddeco/laravel-transip/blob/master/CHANGELOG.md) for a list of made changes.

**Pull request merged**
